### ISSUE TITLE
[BUG] Panic when using 'DisableBatching: true' as producer option

### ISSUE THREAD

**Issue by daluntw** [apache/pulsar-client-go#1098]
#### Expected behavior

no panic when using `DisableBatching: true` as producer option.

#### Actual behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x8a8eaa]

goroutine 1 [running]:

github.com/apache/pulsar-client-go/pulsar.(*partitionProducer).internalFlushCurrentBatch(0xc00c6ccc60)
	/go/pkg/mod/github.com/apache/pulsar-client-go@v0.11.0/pulsar/producer_partition.go:869 +0x2a
github.com/apache/pulsar-client-go/pulsar.(*partitionProducer).runEventsLoop(0xc00c6ccc60)
	/go/pkg/mod/github.com/apache/pulsar-client-go@v0.11.0/pulsar/producer_partition.go:457 +0x1d7
created by github.com/apache/pulsar-client-go/pulsar.newPartitionProducer in goroutine 5713
	/go/pkg/mod/github.com/apache/pulsar-client-go@v0.11.0/pulsar/producer_partition.go:203 +0x9bb
```

when the producer option set to `DisableBatching: true`, the `time.ticker` wil be created and close after a while, when `ticker.Stop()` over 10ms (default value) since created it will cause the ticker still tick, and cause nil pointer dereference eventually.

https://github.com/apache/pulsar-client-go/blob/64c47537311d59a60f8d6463b2ba91a68065354e/pulsar/producer_partition.go#L156-L169

https://github.com/apache/pulsar-client-go/blob/64c47537311d59a60f8d6463b2ba91a68065354e/pulsar/producer_partition.go#L456-L458

#### Steps to reproduce

make application high load, it will randomly show up

#### System configuration
**Pulsar version**: 3.1.0
**pulsar-client-go version**: 0.11.0

**Comment by daluntw** [comment]
as workaround, I set the producer option `BatchingMaxPublishDelay: time.Hour`

thus, the timer should not be tick before `ticker.Stop()`
