### ISSUE TITLE
pulsar-client-go producer_partition  crash

### ISSUE THREAD

**Issue by dsmlily** [apache/pulsar-client-go#143]
### Expected behavior

Tell us what should happen

### Actual behavior

```
worker_1  | panic: runtime error: index out of range [1] with length 1
worker_1  |
worker_1  | goroutine 316 [running]:
worker_1  | github.com/apache/pulsar-client-go/pulsar/internal.ConvertFromStringMap(0xc000f21620, 0xc000ac9430, 0xc00014f788, 0x2)
worker_1  | 	/data/code/Multi-SiteHighAvailabilitySignalServer/thirdparty/src/github.com/apache/pulsar-client-go/pulsar/internal/commands.go:258 +0x265
worker_1  | github.com/apache/pulsar-client-go/pulsar.(*partitionProducer).internalSend(0xc000bd6280, 0xc000f21650)
worker_1  | 	/data/code/Multi-SiteHighAvailabilitySignalServer/thirdparty/src/github.com/apache/pulsar-client-go/pulsar/producer_partition.go:248 +0xb0c
worker_1  | github.com/apache/pulsar-client-go/pulsar.(*partitionProducer).runEventsLoop(0xc000bd6280)
worker_1  | 	/data/code/Multi-SiteHighAvailabilitySignalServer/thirdparty/src/github.com/apache/pulsar-client-go/pulsar/producer_partition.go:205 +0x144
worker_1  | created by github.com/apache/pulsar-client-go/pulsar.newPartitionProducer
worker_1  | 	/data/code/Multi-SiteHighAvailabilitySignalServer/thirdparty/src/github.com/apache/pulsar-client-go/pulsar/producer_partition.go:114 +0x5d8
signal_dockerfiles_worker_1 exited with code 2
```

### Steps to reproduce

How can we reproduce the issue

### System configuration

Pulsar version: x.y

**Comment by cckellogg** [comment]
How did you setup your producer? Can you share the code and any steps to reproduce this error? This will help to debug this.

**Comment by jiazhai** [comment]
@dsmlily Would you please help provide more details as @cckellogg suggested ?

**Comment by dsmlily** [comment]
@jiazhai @cckellogg  Sorry，this problem should be caused by our improper use of golang map.
