### ISSUE TITLE
Flush on unbatched producer panics

### ISSUE THREAD

**Issue by flowchartsman** [apache/pulsar-client-go#897]
Had a call to `producer.Flush()` sitting around in some test code that I forgot to remove after disabling producer batching. After upgrading to head, the tests begin to panic.

```go
producer, err := client.CreateProducer(ProducerOptions{
	Topic:           newTopicName(),
	DisableBatching: true,
})
ID, err := producer.Send(context.Background(), &ProducerMessage{
	Payload: []byte("hello"),
})
producer.Flush()
```

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1005cf756]

goroutine 13 [running]:
github.com/apache/pulsar-client-go/pulsar.(*partitionProducer).internalFlushCurrentBatch(0xc0007bc240)
        /Users/me/go/pkg/mod/github.com/apache/pulsar-client-go@v0.9.1-0.20221129090243-884e13ecf0a1/pulsar/producer_partition.go:810 +0x36
github.com/apache/pulsar-client-go/pulsar.(*partitionProducer).internalFlush(0xc0007bc240, 0xc0006d6018)
        /Users/me/go/pkg/mod/github.com/apache/pulsar-client-go@v0.9.1-0.20221129090243-884e13ecf0a1/pulsar/producer_partition.go:992 +0x3e
github.com/apache/pulsar-client-go/pulsar.(*partitionProducer).runEventsLoop(0xc0007bc240)
        /Users/me/go/pkg/mod/github.com/apache/pulsar-client-go@v0.9.1-0.20221129090243-884e13ecf0a1/pulsar/producer_partition.go:452 +0x114
created by github.com/apache/pulsar-client-go/pulsar.newPartitionProducer
        /Users/me/go/pkg/mod/github.com/apache/pulsar-client-go@v0.9.1-0.20221129090243-884e13ecf0a1/pulsar/producer_partition.go:201 +0xaf6
```

This is because `partitionProducer.internalFlushCurrentBatch()` is called without checking to see if `partitionProducer.batchBuilder` is nil.

#### Expected behavior

NOP?

#### Actual behavior

Panic

**Comment by flowchartsman** [comment]
This issue was duplicated by #1064 and fixed by #1065. Closing this as superceded.
